apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: mcp-backends
  namespace: mcp
spec:
  mcp:
    targets:
      - name: argocd
        static:
          host: argocd-mcp-server.mcp.svc.cluster.local
          port: 3000
          protocol: StreamableHTTP    
      - name: github
        static:
          host: github-mcp-server.mcp.svc.cluster.local
          port: 3000
          protocol: StreamableHTTP
      - name: kagent
        static:
          host: kagent-controller.kagent.svc.cluster.local
          port: 8083
          protocol: StreamableHTTP
      - name: drone
        static:
          host: backend.default.svc.cluster.local
          port: 3002
          protocol: StreamableHTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-route-3000
  namespace: mcp
spec:
  parentRefs:
  - name: agentgateway
    namespace: mcp
    port: 3000
  rules:
    - backendRefs:
      - name: mcp-backends
        group: agentgateway.dev
        kind: AgentgatewayBackend
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route-3001
  namespace: mcp
spec:
  parentRefs:
  - name: agentgateway
    namespace: mcp
    port: 3001
  rules:
    - backendRefs:
      - name: backend
        namespace: default
        port: 3001