apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-mcp-server
  namespace: mcp
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-mcp-server
  namespace: mcp
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    appProtocol: kgateway.dev/mcp
  selector:
    app.kubernetes.io/instance: argocd-mcp-server
    app.kubernetes.io/name: argocd-mcp-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-mcp-server
  namespace: mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: argocd-mcp-server
      app.kubernetes.io/name: argocd-mcp-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/instance: argocd-mcp-server
        app.kubernetes.io/name: argocd-mcp-server
    spec:
      containers:
      - args:
        - -f
        - /config/local.yaml
        command:
        - /adapterbin/agentgateway
        env:
        - name: ARGOCD_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: argocd-mcp-secret
              key: ARGOCD_API_TOKEN
        - name: ARGOCD_BASE_URL
          value: https://argocd-server.argocd.svc.cluster.local:443
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        image: node:24-alpine3.21
        imagePullPolicy: IfNotPresent
        name: mcp-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /adapterbin
          name: binary
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --copy-self
        - /adapterbin/agentgateway
        image: ghcr.io/agentgateway/agentgateway:0.9.0-musl
        imagePullPolicy: IfNotPresent
        name: copy-binary
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /adapterbin
          name: binary
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: argocd-mcp-server
      serviceAccountName: argocd-mcp-server
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: argocd-mcp-server
        name: config
      - emptyDir: {}
        name: binary
---
apiVersion: v1
data:
  local.yaml: |
    binds:
    - listeners:
      - name: default
        protocol: HTTP
        routes:
        - backends:
          - mcp:
              targets:
              - name: argocd-mcp-server
                stdio:
                  args:
                  - argocd-mcp@latest
                  - stdio
                  cmd: npx
                  env:
                    ARGOCD_BASE_URL: https://argocd-server.argocd.svc.cluster.local:443
                    NODE_TLS_REJECT_UNAUTHORIZED: "0"
            weight: 100
          matches:
          - path:
              pathPrefix: /sse
          - path:
              pathPrefix: /mcp
          name: mcp
      port: 3000
    config: {}
kind: ConfigMap
metadata:
  name: argocd-mcp-server
  namespace: mcp

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-mcp-secret
  namespace: mcp
stringData:
  ARGOCD_API_TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjphcGlLZXkiLCJuYmYiOjE3Njk2MTM1MzUsImlhdCI6MTc2OTYxMzUzNSwianRpIjoiOGQ0OTU5ODktYmFmMy00YjAyLTk1ZjctYjZhNWJhN2VjMWYyIn0.kzib3YHa_PrvwWi_jIPEZ1inK2I4brPllckkZUM-GLE"

