apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
  name: argocd-mcp-server
  namespace: mcp
  labels:
    kagent.dev/discovery: disabled
spec:
  deployment:
    args:
    - "argocd-mcp@latest"
    - "stdio"
    env:
      ARGOCD_BASE_URL: "https://argocd-server.argocd.svc.cluster.local:443"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    cmd: npx
    port: 3000
    SecretRefs:
    - name: argocd-mcp-secret
  transportType: stdio
