apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: frontend-httproute
  namespace: default
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Service
      name: agentgateway-proxy
      namespace: default
  rules:
    - matches:
        - path:
            type: Prefix
            value: "/"
      backendRefs:
        - name: frontend
          port: 80
          namespace: default